# Generated by Django 4.2 on 2023-04-09 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0002_userprofile_history_expense_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='left',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
