# Generated by Django 4.2 on 2023-04-09 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0004_remove_budget_left_remove_expense_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='budget',
            field=models.ForeignKey(default='Random', on_delete=django.db.models.deletion.CASCADE, to='appname.budget'),
        ),
    ]
