# Generated by Django 4.2 on 2023-04-11 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0005_expense_budget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='left',
        ),
        migrations.AddField(
            model_name='budget',
            name='left',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
